CREATE TABLE IF NOT EXISTS movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    url_imagem VARCHAR(255),
    trailer_id VARCHAR(255),
    watched_status VARCHAR(255) -- Novo campo para o status de visualização
);

INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('A Bruxa de Blair', '/images/a_bruxa_de_blair.webp', 'zgPiiaLQD5Y', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('A Bruxa', '/images/a_bruxa.webp', 'FE-u6RznkGQ', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Arremate Para o Inferno', '/images/arrateme_para_o_inferno.jpg', 'nltznxDtVzo', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Babadook', '/images/babadook.webp', 'ibHErzMzp2g', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Corra!', '/images/corra.jpg', 'mDGV5UucTu8', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Halloween', '/images/halloween.jpg', 'n72XUX96078', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Hereditário', '/images/hereditario.webp', 'Ui13PlmyZhQ', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Invocação do mal', '/images/invocacao_do_mal.jpg', 'GQrrXceHn2E', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Bêbe de Rosimary', '/images/o_bebe_de_rosimary.jpeg', 'vGJSO-DsZSs', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Brinquedo Assassino', '/images/o_brinquedo_assassino.jpg', 'PMHAPMGXQ9s', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Exorcista', '/images/o_exorcista.jpg', 'cGAZPUKw3lU', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Massacre da Serra Elétrica', '/images/o_massacre_da_serra_eletrica.png', '03HaeTNCUIE', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Sexto Sentido', '/images/o_sexto_sentido.webp', '1WWK9m9FhuQ', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('O Silêncio dos Inocentes', '/images/o_silencio_dos_inocentes.webp', 'UQmpyBY7Xes', NULL);
INSERT INTO movie (nome, url_imagem, trailer_id, watched_status) VALUES ('Sexta Feira 13', '/images/sexta_feira_13.webp', 'dGT2-aWLHDw', NULL);
